title: Abhiram Pamula
logo: /assets/img/headshot.png
#description: text below image
show_description: Environmental and Water Resources Engineer, Marquette University
email: abhiramsivaprasad.pamula@marquette.edu, abhiram.pamula@gmail.com

show_downloads: true
theme: jekyll-theme-minimal
