title: Abhiram Pamula
logo: /assets/img/headshot.png
affiliation: Marquette University
email: abhiramsivaprasad.pamula@marquette.edu, abhiram.pamula@gmail.com

#description: text below image
google_scholar: https://scholar.google.com/

show_downloads: true
theme: jekyll-theme-minimal
