author:
  title: Abhiram S.P. Pamula
  affiliation: Marquette University
  email: 
    - abhiramsivaprasad.pamula@marquette.edu
    - abhiram.pamula@gmail.com
logo: /assets/img/headshot.png
social:
  github: https://github.com/abhiramp1
show_downloads: true
theme: jekyll-theme-minimal

description: |
  Postdoctoral Researcher specializing in water resources and remote sensing applications. Current research focuses on multispectral remote sensing for stormwater management and non-native plant species detection.

