title: Abhiram Pamula
logo: /assets/img/headshot.png
affiliation: Marquette University
email:
  - abhiramsivaprasad.pamula@marquette.edu
  - abhiram.pamula@gmail.com
google_scholar: https://scholar.google.com/citations?user=YOUR_ID
linkedin: https://www.linkedin.com/in/YOUR_PROFILE
github: https://github.com/YOUR_GITHUB
show_downloads: true
theme: jekyll-theme-minimal

# Optional Sections
description: |
  Postdoctoral Researcher specializing in water resources and remote sensing applications. Current research focuses on hyperspectral remote sensing for stormwater management and non-native plant species detection.

# Projects Section (Example)
projects:
  - title: Multispectral Remote Sensing for Stormwater Management
    description: Using advanced remote sensing techniques to improve land use strategies.
    link: /projects/stormwater-management

  - title: Non-Native Plant Detection Using Remote Sensing
    description: Leveraging hyperspectral data for invasive species identification.
    link: /projects/plant-detection

